### ISSUE TITLE
Can't go to connection settings again

### ISSUE THREAD

**Issue by danreg** [hansworst24/Ticz#9] opened 2016-03-08 09:27 UTC
Hi,

when starting Ticz the first time, a connection view appears. Once you have configured (right or wrong makes no difference) you can't go back to configuration view. A entry in the bottom menu would be nice.

Maybe I will start to contribute to this app soon (Could do german translation, or smaller bugfixes)

**Comment by hansworst24** [comment] 2016-03-13 15:10
@danreg,

I just tested with v1.6 (Store version) as well as latest non-store build on Phone and Desktop. For both scenarios I was succesfully able to use the Back button (hardware back for Phone, Top-left corner back button for Desktop) to go back one setting in the menu. 

which platform did you test it on ?

**Comment by danreg** [comment] 2016-03-13 16:54
I'm using Windows Mobile 10 on a Lumia 950. I can't get a working connection with ticz. When I try to connect to my domoticz server it only says: Hmm..doesn't work: Unauthorized.
Using 192.168.1.31 and Port 8080 with my credentials

Using another domoticz app on windows mobile, with same connection data is working.

Anyway on the next start of the app, I can't get back to the connection dialog. It is only showing an empty screen with no devices/rooms. I can't do anything.

Pressing back button, closes the app

**Comment by hansworst24** [comment] 2016-03-13 17:12
@danreg 
Are you sure you're using Basic-Auth on Domoticz ? Also please double check that when you type in the username, it doesn't start with a Capital (WinPhone does that automatically)

you can also try (last resort) to add the 192.168.1.\* range to the "Local Networks (no username/password)" section in Domoticz, this way it will not require any credentials when you use it on local network

ps : I'll work on the menu thing, in case you had wrong/no IP settings. Indeed you should be able to go back to the server settings :)

**Comment by hansworst24** [comment] 2016-03-13 17:16
@danreg also : could you send me a screenshot of your Lumia 950 once you started the app and nothing happens ? Maybe for some reason a part of the screen has fallen off, there should be a menu button visible ! :)

**Comment by danreg** [comment] 2016-03-14 09:23
I'm using th same credentials and ip+port than in the other domoticz windows mobile app, where it is working. So I think the issue must in ticz

Here are the screenshots, after no connection were possible and restarting the app.

![wp_ss_20160314_0003](https://cloud.githubusercontent.com/assets/16964633/13739942/55ca020c-e9ce-11e5-803c-533cf01fc743.png)
![wp_ss_20160314_0001](https://cloud.githubusercontent.com/assets/16964633/13739943/55d74e30-e9ce-11e5-8c21-6e0c2b575150.png)

**Comment by hansworst24** [comment] 2016-03-14 09:37
thanks @danreg  , and when you click the hamburger menu (the three stripes), it doesn't open at all ? or remains empty ?

out of curiousity ; which domoticz app are you using that works ? Because I found only 1, and that one didn't allow ME to connect in any way :) Maybe it's an issue related to on what OS Domoticz is running.. ? On what OS is your Domoticz server running ?

**Comment by hansworst24** [comment] 2016-03-14 09:45
I think the issue is two-fold ;
- authentication issue (for whatever reason)
- your phone having on-screen buttons for Back/Home/Search. I currently believe that that is causing certain controls not to be visible in the Hamburger menu, and update messages (which also appear in the bottom) not to show up.

I'll check the second point with an emulator, to see if I can replicate the issue

**Comment by danreg** [comment] 2016-03-14 09:47
First Screenshot shows the Hamburger menu after pressing the three stripes Button. 

I'm running domoticz on a rpi with raspbian. Currently I'm using this domoticz app https://www.microsoft.com/de-de/store/apps/domoticz/9nblggh16879

U need the enter ip adress starting with http://

**Comment by hansworst24** [comment] 2016-03-14 13:32
@danreg what exact version of Windows runs on your phone ? I test against 10.0.586.0 emulators, and all show the additional menu buttons (the ones you don't see) properly.

Can you test the app on a Windows 10 desktop/laptop, to see if the behaviour is the same ?

ps : got the other app working. Works, but mine is way better (if it works :) :) :)

**Comment by danreg** [comment] 2016-03-14 14:18
Could you post a Screenshot of the additional button?

**Comment by hansworst24** [comment] 2016-03-14 14:38
you should see the 4 buttons below in the menu, this is from a unconfigured Ticz on a emulator. The first button brings you back to Settings, the second button reloads everything, the 3rd is the security panel and the 4th is "About". It shouldn't matter if you are connected to Domoticz or not... they should be there :(

![buttons](https://cloud.githubusercontent.com/assets/7300919/13747808/5e3d5b6a-e9fa-11e5-9dd8-1cd5522510fc.png)

**Comment by hansworst24** [comment] 2016-03-15 16:26
@danreg I assume the screen doesn't help you much further. Were you able to test on a Windows 10 PC ?

**Comment by danreg** [comment] 2016-03-15 17:01
Yes I tried it today on my Windows 10 PC, and the 4 symbols are visible. Anyway I get the same error message connecting to domoticz. When I find some time, I could try to debug it, to find the issue

**Comment by hansworst24** [comment] 2016-03-15 20:06
worst case scenario : I can run the debug version out of visual studio against your setup if it's accessible from outside, and you provide a temporary user/password... It's an intruiging issue which I don't understand at all..

**Comment by danreg** [comment] 2016-03-17 18:15
![wp_ss_20160317_0001](https://cloud.githubusercontent.com/assets/16964633/13856244/8c72a388-ec74-11e5-84a7-5519753b4a67.png)

After latest update it looks like this

**Comment by hansworst24** [comment] 2016-03-17 20:21
Good ! Well, bad :) But I now see the small dark line just above the hamburger menu, which indicates that the icons are underneath the hamburger menu bar.... I will need to find a way to detect if the phone has soft-keys or not, and adjust the margin for the main screen accordingly... I also need to be able to reproduce it..... :)

**Comment by hansworst24** [comment] 2016-03-17 21:09
ok... I think I solved the margin thing, at least on a emulator with soft-keys it appears fine now.

Regarding the unautorized message : Any chance that there are funny characters in either the username or password you are using ? ç, or other funny stuff ? If so, maybe you can give me a test user/pass containing those characters, just to see if that causes the problem and I can replicate it here

**Comment by hansworst24** [comment] 2016-05-09 07:21
@danreg 

the issue still persists or has it been solved ?

**Comment by danreg** [comment] 2016-05-09 17:11
Nope still not working. I had not the time yet to debug it with visual studio.
Something has changed in the app. When I press "test connection" it says "Hurray" 
but on the main screen there is still an error message : "Error loading Domoticz settings (Unauthorized)"

**Comment by hansworst24** [comment] 2016-05-10 12:34
If you want I can debug your setup from here this evening, With a temp user/password you can set. It should be a quick fix....

**Comment by danreg** [comment] 2016-05-28 13:29
Sorry for the late answer. I think because of my ISP you can't connect to me from remote.
I finally got the visual studio debugging working. Maybe this screenshot could help?

![screen](https://cloud.githubusercontent.com/assets/16964633/15627585/c5c25172-24e8-11e6-990a-8c0b8c90541c.png)
This breakpoint is reached when clicking on "test connection"

**Comment by danreg** [comment] 2016-05-28 13:40
Oh man! Guess what... I found the reason why it is not working!
I hadn't set Website Protection to "Basic auth". After selecting basic auth, ticz is working.
https://www.domoticz.com/wiki/Application_Settings#Website_Protection

Do you have any idea why it is not wirking with the other option? (don't know the english option, have it in german, should be something with login page)

**Comment by hansworst24** [comment] 2016-05-29 18:42
grrreat :smile: Happy to hear it is working for you now ! In the latest Ticz releases I mentioned in the Server Settings page that basic-auth should be turned on, as some people overlooked it :smile: 

I actualy have never tried to let the Login Page work, as most other tools I've seen that require a login, only work with basic-auth. I therefore presumed that trying to use a Login Page is too troublesome to insert in an App, or maybe not possible at all.

If you connect from remote (WAN), probably it's recommended to use SSL as that adds a level of encryption to it.

I'll close the issue now !

**Closed as completed by hansworst24** 2016-05-29 18:42 UTC
